

server.port = 8072

spring.application.name = movie-info-service

api.key = 58f9f3ba226240c8da24834c3fc98e85

logging.pattern.console=%d{HH:mm:ss} %-5level [${spring.application.name}] %logger{36} - %msg%n

